Updates

diff --git a/bin/batcap b/bin/batcap
--- a/bin/batcap
+++ b/bin/batcap
@@ -6,7 +6,7 @@ prgname=${0##*/}
 
 for i in /sys/class/power_supply/BAT${1:-*}; do
     [[ -d $i ]] || {
-        echo "$prgname: cannot access $i"  >&2
+        echo "$prgname: cannot access $i" >&2
         exit 1
     }
     . "$i/uevent"
