Updates

diff --git a/bin/dispcal-calibrate b/bin/dispcal-calibrate
--- a/bin/dispcal-calibrate
+++ b/bin/dispcal-calibrate
@@ -1,17 +1,35 @@
 #!/usr/bin/env bash
 
-set -eu
+set -eu -o pipefail
 
+prgname=${0##*/}
+
+mkdir -p ~/.local/share/icc
 cd ~/.local/share/icc
 
-gopts=(-v2 -d2 -ye -H -F -P '0.5,0.5,2.0' -Ibw)
+echo $'\n--------------------------------------------------'
+echo '> Select display / monitor to continue:'
 
-echo $'\n> dispcal:'
+readarray -t dall < <(dispcal -h |& LC_ALL=C grep -F Output | sed -r 's/^\s*//')
+printf '%s\n' "${dall[@]}"
+echo
+
+read -N1 -rsp 'Your choice: ' dsel
+echo
+
+if [[ ! $dsel =~ ^[1-9]$ ]] || (( dsel > ${#dall[@]} )); then
+    echo "$prgname: error: invalid choice" && exit 2
+fi
+printf '%s\n' "${dall[$((dsel-1))]}"
+
+echo $'\n--------------------------------------------------'
+echo $'> dispcal:'
+gopts=(-v2 -d$dsel -ye -P '0.5,0.5,2.0')
 dispcal "${gopts[@]}" -m -q m -t 6500 -g 2.2 out
 
 echo $'\n--------------------------------------------------'
 echo '> targen:'
-targen -v2 -d 3 -G -e 4 -s 5 -g 17 -f 64 out
+targen -d 3 -G -e 4 -s 5 -g 17 -f 64 out
 
 echo $'\n--------------------------------------------------'
 echo '> dispread:'
@@ -19,7 +37,5 @@ dispread "${gopts[@]}" -N -k out.cal out
 
 echo $'\n--------------------------------------------------'
 echo '> colprof:'
-colprof -v2 -D 'model' \
-           -C 'copyright' \
-           -q u -a G -Z p -n c out
+colprof -v2 -D 'model' -C 'copyright' -q u -a G -Z p -n c out
 echo
