Updates

diff --git a/bin/system/hdinfo b/bin/system/hdinfo
--- a/bin/system/hdinfo
+++ b/bin/system/hdinfo
@@ -2,11 +2,6 @@
 
 set -eu
 
-if (( EUID )); then
-    echo 'This script must be run with root privileges.' >&2
-    exit 1
-fi
-
 prgname=${0##*/}
 
 _usage() {
@@ -29,8 +24,13 @@ shift $((OPTIND-1))
 
 target=$1
 
-if [[ ! -e $target ]]; then
-    echo "$prgname: cannot access $target: No such device" >&2
+if [[ ! -b $target ]]; then
+    echo "$prgname: cannot access $target: No such block device" >&2
+    exit 1
+fi
+
+if (( EUID )); then
+    echo 'This script must be run with root privileges.' >&2
     exit 1
 fi
 
